const $=id=>document.getElementById(id);const app=$("app"),questionArea=$("questionArea"),noticeArea=$("noticeArea"),nextBtn=$("nextBtn"),backBtn=$("backBtn"),progressBar=$("progressBar"),progressLabel=$("progressLabel"),stopScreen=$("stopScreen"),finalScreen=$("finalScreen"),stopTitle=$("stopTitle"),stopMessage=$("stopMessage"),estimate=$("estimate"),estimateExplanation=$("estimateExplanation"),checklist=$("checklist");
const answers={};let current=0;
const questions=[
{id:"sequenced",number:"1",title:"Is the data already sequenced?",type:"single",options:[{value:"yes",label:"Yes"},{value:"no",label:"No"}]},
{id:"sequencingProvider",number:"1.1",title:"Who performed the sequencing?",type:"multiple",options:[{value:"outsourced",label:"We outsourced the sequencing / We sequenced it ourselves",description:"Make sure you have this metadata in order. Biomaterial IDs are important to us.",weeks:2},{value:"singleCell",label:"Single Cell facility",description:"Make sure to ask them for the required metadata information.",weeks:2},{value:"diagnostics",label:"Data was sequenced by the biobank / genomics core / diagnostics"}]},
{id:"maxima",number:"2",title:"Do all the samples you plan to submit come from patients at the Máxima?",type:"single",options:[{value:"allMaxima",label:"Yes, all our samples belong to Máxima patients"},{value:"partExternal",label:"No, part of our samples come from external individuals",description:"Our submission data model uses Individual, Diagnosis, Biosource and Biomaterial ID. External individuals need identifiers such as PMCIDs. Contact the Big Data Core early.",weeks:2},{value:"allExternal",label:"No, all my samples come from external individuals",description:"Our submission data model uses Individual, Diagnosis, Biosource and Biomaterial ID. External individuals need identifiers such as PMCIDs. Contact the Big Data Core early."}]},
{id:"externalSharing",number:"2.1",title:"For your external samples, are you allowed to share and make the data available?",type:"single",options:[{value:"unknown",label:"I don't know",description:"Before reaching out, make sure you have a data sharing agreement or material sharing agreement that states what you are allowed to do with the data. You may share it with Big Data Core."},{value:"no",label:"No"},{value:"yes",label:"Yes",description:"Good! When talking with the Big Data Core, make sure to have the data sharing agreement / material sharing agreement in hand. You are ready to submit!"}]},
{id:"dataType",number:"3",title:"What data types/libraries does your dataset include?",type:"multiple",options:[{value:"bulk",label:"Bulk sequencing (RNA-seq, WES, WGS, …)"},{value:"singleCell",label:"Single-cell sequencing (RNA-seq, …)",description:"Single-cell doesn't always fit into our existing data model. Have a good overview of how samples were prepared and how replicates were handled."},{value:"spatial",label:"Spatial sequencing"},{value:"nanopore",label:"Nanopore"},{value:"methylation",label:"Methylation data",description:"Methylation data requires slightly more information. Pay attention to the needed metadata!"},{value:"other",label:"Other"}]},
{id:"samples",number:"4",title:"How many samples are included in your dataset?",type:"single",options:[{value:"under100",label:"Below 100",weeks:0},{value:"100to500",label:"Between 100–500",weeks:1},{value:"500to1000",label:"Between 500–1000",weeks:2},{value:"over1000",label:"More than 1000",weeks:3}]}
];
function visible(){let v=[questions[0]];if(answers.sequenced==="yes")v.push(questions[1]);v.push(questions[2]);if(["partExternal","allExternal"].includes(answers.maxima))v.push(questions[3]);v.push(questions[4],questions[5]);return v}
function selected(q,val){return q.type==="multiple"?(answers[q.id]||[]).includes(val):answers[q.id]===val}
function render(){const v=visible(),q=v[current];if(!q)return final();progressLabel.textContent=`Question ${q.number} of ${v.length}`;progressBar.style.width=`${(current+1)/v.length*100}%`;questionArea.innerHTML=`<div class="question-number">Question ${q.number}</div><div class="question">${q.title}</div><div id="options"></div>`;const box=$("options");q.options.forEach(o=>{const l=document.createElement("label");l.className="option"+(selected(q,o.value)?" selected":"");l.innerHTML=`<input type="${q.type==="multiple"?"checkbox":"radio"}" name="${q.id}" value="${o.value}" ${selected(q,o.value)?"checked":""}><div class="option-title">${o.label}</div>${o.description?`<div class="option-description">${o.description}</div>`:""}`;l.querySelector("input").addEventListener("change",e=>{if(q.type==="single")answers[q.id]=e.target.value;else{answers[q.id]=answers[q.id]||[];answers[q.id]=e.target.checked?[...new Set([...answers[q.id],e.target.value])]:answers[q.id].filter(x=>x!==e.target.value)};renderNotice(q);if(q.id==="sequenced"&&answers.sequenced==="no")stop("You are not yet ready to submit your data.","Once you receive, analysed and shared your analysis, fill out the questionnaire when you already have your data and you plan to submit it.");if(q.id==="externalSharing"&&answers.externalSharing==="no")stop("We cannot proceed with the submission yet.","Without authorization from the data/samples provider we are not allowed to proceed with the submission. Reach out to the provider and request them to share the data on your behalf.");});box.appendChild(l)});renderNotice(q);backBtn.classList.toggle("hidden",current===0);nextBtn.textContent=current===v.length-1?"Get my estimate":"Continue"}
function renderNotice(q){noticeArea.innerHTML="";const vals=q.type==="multiple"?(answers[q.id]||[]):[answers[q.id]];const msgs=q.options.filter(o=>vals.includes(o.value)&&o.description).map(o=>`<p>${o.description}</p>`).join("");if(msgs)noticeArea.innerHTML=`<div class="notice"><strong>Please note</strong>${msgs}</div>`}
function next(){const v=visible(),q=v[current],a=answers[q.id];if(!a||(q.type==="multiple"&&!a.length)){noticeArea.innerHTML='<div class="notice"><strong>Please select an answer</strong><p>Choose an option before continuing.</p></div>';return}if(q.id==="sequenced"&&a==="no")return stop("You are not yet ready to submit your data.","Once you receive, analysed and shared your analysis, fill out the questionnaire when you already have your data and you plan to submit it.");if(q.id==="externalSharing"&&a==="no")return stop("We cannot proceed with the submission yet.","Without authorization from the data/samples provider we are not allowed to proceed with the submission. Reach out to the provider and request them to share the data on your behalf.");current++;current>=visible().length?final():render()}
function stop(t,m){app.classList.add("hidden");finalScreen.classList.add("hidden");stopScreen.classList.remove("hidden");stopTitle.textContent=t;stopMessage.textContent=m}
function addedWeeks(){let w=0;if((answers.sequencingProvider||[]).some(x=>["outsourced","singleCell"].includes(x)))w+=2;if(answers.maxima==="partExternal")w+=2;const s=answers.samples;return w+({under100:0,100to500:1,500to1000:2,over1000:3}[s]||0)}
function final(){const w=addedWeeks();estimate.textContent=w?`2 months + ${w} week${w==1?"":"s"}`:"2 months";estimateExplanation.textContent=`Normal timeline: 2 months, plus ${w} additional week${w==1?"":"s"} based on your answers.`;let items=["Your project and related datasets are already registered in FAIR Wizard, following the relevant instructions."];if((answers.sequencingProvider||[]).some(x=>x!=="diagnostics"))items.push("Make sure you know the protocol used during the sequencing of your cells. If you don't, ask how the sequencing was performed and how samples/cells were treated.");if(["partExternal","allExternal"].includes(answers.maxima)){items.push("Make sure you know the provenance of the sample, e.g. the sex of the individual who provided the sample, tumor type and topography. Contact the relevant provider in advance.");items.push("Because the submission data model relies on identifiers for each class, make sure identifiers exist for each individual (including PMCIDs where required).")}if((answers.dataType||[]).includes("methylation"))items.push("Prepare the relevant assay information for the methylation data in advance.");checklist.innerHTML=items.map(x=>`<li>${x}</li>`).join("");app.classList.add("hidden");stopScreen.classList.add("hidden");finalScreen.classList.remove("hidden")}
function restart(){Object.keys(answers).forEach(k=>delete answers[k]);current=0;stopScreen.classList.add("hidden");finalScreen.classList.add("hidden");app.classList.remove("hidden");render()}
nextBtn.onclick=next;backBtn.onclick=()=>{if(current>0){current--;render()}};$("restartStop").onclick=restart;$("restartFinal").onclick=restart;render();
